### PR TITLE
Unique mutable

### PR DESCRIPTION
**Pull request by panagosg7**
Special Mutability class UniqueMutability to prolong the phase of initializing objects.

See: 

https://github.com/UCSD-PL/RefScript/blob/unique_mutable/tests/pos/classes/init-02.ts

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Nice, can you type this example without the if test but with a suitable signature for createFoo?

**Comment by panagosg7** [comment]
I pushed two more (not sure if this is what you're asking for):
https://github.com/UCSD-PL/RefScript/blob/master/tests/pos/classes/init-03.ts
https://github.com/UCSD-PL/RefScript/blob/master/tests/neg/classes/init-03.ts

**Comment by ranjitjhala** [comment]
No I meant init-02 but with a signature like


/*@ createFoo :: () => { Foo<Immutable> | v.f = 10 } */

On Mon, Feb 23, 2015 at 5:39 PM, Panagiotis Vekris <notifications@github.com
> wrote:

> I pushed two more (not sure if this is what you're asking for):
>
> https://github.com/UCSD-PL/RefScript/blob/master/tests/pos/classes/init-03.ts
>
> https://github.com/UCSD-PL/RefScript/blob/master/tests/neg/classes/init-03.ts
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UCSD-PL/RefScript/pull/99#issuecomment-75682536>.
>



-- 
Ranjit.

**Comment by panagosg7** [comment]
We've dropped support for Keyval- like predicates

**Comment by ranjitjhala** [comment]
Then what exactly is in the environment after the if test? How does the thing know that the value of the infield equals 10 at assertat?

**Comment by panagosg7** [comment]
It's because there is a separate temp variable added to the environment for
each immutable field. So both accesses expose that same variable.

**Pull request merged**
