### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by panagosg7**
Mostly in the size of the fq files.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Nice, did this have much effect on the run times?

**Comment by panagosg7** [comment]
It speeds up most tests, including navier-stokes but the bottleneck were the expensive qualifiers to begin with, so not a dramatic change.

BTW, the latest merge in FP has broken RefScript. I temporarily use: 
https://github.com/panagosg7/liquid-fixpoint
instead.

**Comment by ranjitjhala** [comment]
Can you tell me what is broken/breaks (in FP) ? I am working on a separate
branch so there *shouldn't* have been breaks...

On Thu, Apr 16, 2015 at 7:09 AM, Panagiotis Vekris <notifications@github.com
> wrote:

> It speeds up most tests, including navier-stokes but the bottleneck were
> the expensive qualifiers to begin with, so not a dramatic change.
>
> BTW, the latest merge in FP has broken RefScript. I temporarily use:
> https://github.com/panagosg7/liquid-fixpoint
> instead.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UCSD-PL/RefScript/pull/124#issuecomment-93613893>.
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
Just send a snippet of the compile error?

On Thu, Apr 16, 2015 at 7:17 AM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> Can you tell me what is broken/breaks (in FP) ? I am working on a separate
> branch so there *shouldn't* have been breaks...
>
> On Thu, Apr 16, 2015 at 7:09 AM, Panagiotis Vekris <
> notifications@github.com> wrote:
>
>> It speeds up most tests, including navier-stokes but the bottleneck were
>> the expensive qualifiers to begin with, so not a dramatic change.
>>
>> BTW, the latest merge in FP has broken RefScript. I temporarily use:
>> https://github.com/panagosg7/liquid-fixpoint
>> instead.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UCSD-PL/RefScript/pull/124#issuecomment-93613893>.
>>
>
>
>
> --
> Ranjit.
>



-- 
Ranjit.

**Comment by panagosg7** [comment]
There were some commits in parallel to my last PR which might be relevant.

It's not a compile error. FP gives a bad constraint to almost all tests.
I haven't tried to fix it yet -- it might be sth trivial. Here's the fq file for negate (for example):
https://gist.github.com/panagosg7/f459b9612d33b71f0495

**Comment by ranjitjhala** [comment]
ok, i'll take a look!

On Thu, Apr 16, 2015 at 7:31 AM, Panagiotis Vekris <notifications@github.com
> wrote:

> There were some commits in parallel to my last PR which might be relevant.
>
> It's not a compile error. FP gives a bad constraint to almost all tests.
> I haven't tried to fix it yet -- it might be sth trivial. Here's the fq
> file for negate (for example):
> https://gist.github.com/panagosg7/f459b9612d33b71f0495
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UCSD-PL/RefScript/pull/124#issuecomment-93616705>.
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
hmm. odd, I think this may have to do with your changes to fixpoint.native
-- I have not touched it in a long time. Can you take a look?


On Thu, Apr 16, 2015 at 7:33 AM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> ok, i'll take a look!
>
> On Thu, Apr 16, 2015 at 7:31 AM, Panagiotis Vekris <
> notifications@github.com> wrote:
>
>> There were some commits in parallel to my last PR which might be relevant.
>>
>> It's not a compile error. FP gives a bad constraint to almost all tests.
>> I haven't tried to fix it yet -- it might be sth trivial. Here's the fq
>> file for negate (for example):
>> https://gist.github.com/panagosg7/f459b9612d33b71f0495
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UCSD-PL/RefScript/pull/124#issuecomment-93616705>.
>>
>
>
>
> --
> Ranjit.
>



-- 
Ranjit.

**Pull request merged**
